"""
Django settings for Project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement (.env à la racine du projet)
# Le dossier racine est un niveau au-dessus de BASE_DIR (APPLICATION/)
env_path = os.path.join(BASE_DIR.parent, '.env')
if os.path.exists(env_path):
    load_dotenv(env_path)
else:
    # Fallback si lancé depuis le dossier Project
    load_dotenv(os.path.join(BASE_DIR, '.env'))


# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
# ALWAYS_EAGER dépend de l'environnement
CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_ALWAYS_EAGER', 'False').lower() in ('true', '1', 'yes') or os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER
# Timeouts et retry logic
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes max
CELERY_TASK_SOFT_TIME_LIMIT = 250  # Alerte à 250s
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_BROKER_POOL_KWARGS = {
    'connection_kwargs': {
        'socket_connect_timeout': 5,
        'socket_keepalive': True,
    },
    'max_retries': 3,
}


# ===================================
# VALIDATION DES VARIABLES CRITIQUES
# ===================================
def get_required_env(key: str, default=None):
    """
    Récupère une variable d'environnement.
    Si default=None, lève une erreur si la variable n'existe pas.
    """
    value = os.getenv(key, default)
    if value is None:
        raise ValueError(
            f"Variable d'environnement manquante: {key}\n"
            f"Vérifiez que votre fichier .env contient cette variable."
        )
    return value

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_required_env('SECRET_KEY')


# DEBUG
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')
# Hosts autorisés - validation stricte
if DEBUG:
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
else:
    allowed_hosts = os.getenv('ALLOWED_HOSTS')
    if not allowed_hosts:
        raise ValueError(
            "ALLOWED_HOSTS must be configured in production (.env file)\n"
            "Format: ALLOWED_HOSTS=api.yourdomain.com,yourdomain.com"
        )
    ALLOWED_HOSTS = allowed_hosts.split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',  
    'Accounts',
    'Wallet',
    'Offer',
    'Suggestions',
    'Notifications',
    'django_celery_beat',
]


# CORS Configuration
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://localhost:8080' if DEBUG else ''
).split(',') if os.getenv('CORS_ALLOWED_ORIGINS') or DEBUG else []
if not DEBUG and not CORS_ALLOWED_ORIGINS:
    raise ValueError("CORS_ALLOWED_ORIGINS must be configured in production (.env file)")
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/hour',
        'user': '1000/day',
        'deposit': '10/hour',
        'withdrawal': '5/hour',
        'offer_create': '20/hour',
        'offer_accept': '30/hour',
        'kyc_upload': '3/hour',
    }
}

AUTH_USER_MODEL = 'Accounts.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database logic
if os.getenv('DATABASE_URL') or os.getenv('DATABASE_ENGINE') == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_required_env('DATABASE_NAME'),
            'USER': get_required_env('DATABASE_USER'),
            'PASSWORD': get_required_env('DATABASE_PASSWORD'),
            'HOST': os.getenv('DATABASE_HOST', 'localhost'),
            'PORT': os.getenv('DATABASE_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Caching Configuration
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'alsaba',
            'TIMEOUT': 300,
        }
    }


# Email Configuration (Set to Console for fallback, as project uses SMS-only)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@alsaba.com')

# Validation stricte des clés API
DIDIT_API_KEY = os.getenv('DIDIT_API_KEY')
if not DIDIT_API_KEY:
    if not DEBUG:
        raise ValueError("DIDIT_API_KEY must be configured in production (.env file)")
    DIDIT_API_KEY = 'dev-key-placeholder'
elif DIDIT_API_KEY == 'your-key-here':
    raise ValueError("DIDIT_API_KEY: Do not use default placeholder key! Configure in .env")


# Flutterwave Configuration avec validations
FLUTTERWAVE_ENVIRONMENT = os.getenv('FLUTTERWAVE_ENVIRONMENT', 'sandbox' if DEBUG else 'production')
# Sandbox
FLUTTERWAVE_SANDBOX_CLIENT_ID = os.getenv('FLUTTERWAVE_SANDBOX_CLIENT_ID', '')
FLUTTERWAVE_SANDBOX_CLIENT_SECRET = os.getenv('FLUTTERWAVE_SANDBOX_CLIENT_SECRET', '')
FLUTTERWAVE_SANDBOX_ENCRYPTION_KEY = os.getenv('FLUTTERWAVE_SANDBOX_ENCRYPTION_KEY', '')
FLUTTERWAVE_SANDBOX_BASE_URL = 'https://developersandbox-api.flutterwave.com'
FLUTTERWAVE_SANDBOX_AUTH_URL = 'https://idp.flutterwave.com/realms/flutterwave/protocol/openid-connect/token'
# Production
FLUTTERWAVE_PRODUCTION_CLIENT_ID = os.getenv('FLUTTERWAVE_PRODUCTION_CLIENT_ID', '')
FLUTTERWAVE_PRODUCTION_CLIENT_SECRET = os.getenv('FLUTTERWAVE_PRODUCTION_CLIENT_SECRET', '')
FLUTTERWAVE_PRODUCTION_ENCRYPTION_KEY = os.getenv('FLUTTERWAVE_PRODUCTION_ENCRYPTION_KEY', '')
FLUTTERWAVE_PRODUCTION_BASE_URL = 'https://api.flutterwave.com'
FLUTTERWAVE_PRODUCTION_AUTH_URL = 'https://idp.flutterwave.com/realms/flutterwave/protocol/openid-connect/token'
# URLs et Secrets communs
FLUTTERWAVE_REDIRECT_URL = os.getenv('FLUTTERWAVE_REDIRECT_URL', 'https://google.com')
FLUTTERWAVE_SECRET_KEY = os.getenv('FLUTTERWAVE_SECRET_KEY')
FLUTTERWAVE_PUBLIC_KEY = os.getenv('FLUTTERWAVE_PUBLIC_KEY')
FLUTTERWAVE_ENCRYPTION_KEY = os.getenv('FLUTTERWAVE_ENCRYPTION_KEY')
FLUTTERWAVE_WEBHOOK_SECRET = os.getenv('FLUTTERWAVE_WEBHOOK_SECRET')
FLUTTERWAVE_TIMEOUT = int(os.getenv('FLUTTERWAVE_TIMEOUT', '30'))
FLUTTERWAVE_MAX_RETRIES = int(os.getenv('FLUTTERWAVE_MAX_RETRIES', '3'))
FLUTTERWAVE_RETRY_DELAY = int(os.getenv('FLUTTERWAVE_RETRY_DELAY', '2'))
# Validation stricte pour production
if not DEBUG:
    if FLUTTERWAVE_ENVIRONMENT == 'production':
        required_keys = [
            ('FLUTTERWAVE_PRODUCTION_CLIENT_ID', FLUTTERWAVE_PRODUCTION_CLIENT_ID),
            ('FLUTTERWAVE_PRODUCTION_CLIENT_SECRET', FLUTTERWAVE_PRODUCTION_CLIENT_SECRET),
            ('FLUTTERWAVE_PUBLIC_KEY', FLUTTERWAVE_PUBLIC_KEY),
            ('FLUTTERWAVE_WEBHOOK_SECRET', FLUTTERWAVE_WEBHOOK_SECRET),
        ]
        for key_name, key_value in required_keys:
            if not key_value:
                raise ValueError(f"Production: {key_name} must be configured in .env")
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

import structlog
import os
from .logging_utils import redact_sensitive_data

# Créer le dossier logs s'il n'existe pas
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)


# Celery Beat Schedule - configurable
CELERY_BEAT_SCHEDULE = {
    'check-expired-offers-every-10-min': {
        'task': 'Offer.tasks.check_expired_offers',
        'schedule': float(os.getenv('OFFER_CHECK_INTERVAL', '600')),
    },
    'reconcile-transactions-every-30-min': {
        'task': 'Wallet.tasks.reconcile_transactions',
        'schedule': float(os.getenv('TRANSACTION_RECONCILE_INTERVAL', '1800')),
    },
}

LOGGING = {

    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # Format lisible pour fichiers .log
        'detailed': {
            'format': '[{asctime}] {levelname:8s} | {name:30s} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Format console avec couleurs (via structlog)
        'console_formatter': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.dev.ConsoleRenderer(colors=True),
        },
    },
    'handlers': {
        # Console avec couleurs
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console_formatter',
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
        # Fichier général (tous les niveaux)
        'file_all': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'alsaba.log'),
            'formatter': 'detailed',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 10,
            'encoding': 'utf-8',
        },
        # Fichier INFO uniquement
        'file_info': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'info.log'),
            'formatter': 'detailed',
            'level': 'INFO',
            'maxBytes': 5242880,  # 5MB
            'backupCount': 5,
            'encoding': 'utf-8',
        },
        # Fichier ERROR et CRITICAL
        'file_error': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'error.log'),
            'formatter': 'detailed',
            'level': 'ERROR',
            'maxBytes': 5242880,  # 5MB
            'backupCount': 10,
            'encoding': 'utf-8',
        },
        # Fichier DEBUG (seulement en mode DEBUG)
        'file_debug': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'debug.log'),
            'formatter': 'detailed',
            'level': 'DEBUG',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 3,
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # Logger racine (tous les modules)
        '': {
            'handlers': ['console', 'file_all', 'file_info', 'file_error'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        # Logger spécifique Wallet
        'Wallet': {
            'handlers': ['console', 'file_all', 'file_info', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger spécifique Accounts
        'Accounts': {
            'handlers': ['console', 'file_all', 'file_info', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger spécifique Offer
        'Offer': {
            'handlers': ['console', 'file_all', 'file_info', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger Django (requêtes, etc.)
        'django': {
            'handlers': ['console', 'file_all'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger requêtes DB (désactivé par défaut pour éviter spam)
        'django.db.backends': {
            'handlers': ['file_debug'] if DEBUG else [],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Configuration structlog (pour logs structurés lisibles)
structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        redact_sensitive_data, # Custom processor for PCI-DSS
        structlog.processors.TimeStamper(fmt="%Y-%m-%d %H:%M:%S", utc=False),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)



# Monitoring avec Sentry
SENTRY_DSN = os.getenv('SENTRY_DSN')
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development' if DEBUG else 'production')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        integrations=[DjangoIntegration(), CeleryIntegration()],
        traces_sample_rate=0.1,
        send_default_pii=False,
        ignore_errors=[
            'rest_framework.exceptions.NotFound',
            'rest_framework.exceptions.PermissionDenied',
        ],
    )

# Didit settings - validation stricte
DIDIT_WEBHOOK_SECRET = os.getenv('DIDIT_WEBHOOK_SECRET')
if not DIDIT_WEBHOOK_SECRET:
    if not DEBUG:
        raise ValueError("Production: DIDIT_WEBHOOK_SECRET must be configured in .env for security")
    DIDIT_WEBHOOK_SECRET = 'dev-webhook-secret'
