# Generated by Django 5.2.10 on 2026-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'Système'), ('security', 'Sécurité'), ('transaction', 'Transaction'), ('offer', 'Offre P2P'), ('marketing', 'Promotion'), ('suggestion', 'Suggestion IA')], default='system', max_length=20),
        ),
    ]
