# Generated by Django 5.2.10 on 2026-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='registration_id',
            field=models.CharField(blank=True, help_text="Token FCM unique de l'appareil (Push Notification)", max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone au format E.164 (ex: +221771234567)', max_length=20, null=True),
        ),
    ]
