# Generated by Django 5.2.10 on 2026-01-31 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone au format E.164 (ex: +221771234567)', max_length=20, null=True, unique=True),
        ),
    ]
