# Generated by Django 5.2.10 on 2026-01-31 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_alter_device_unique_together_device_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'phone_number')},
        ),
        migrations.RemoveField(
            model_name='device',
            name='fcm_token',
        ),
    ]
