# Generated by Django 5.2.10 on 2026-02-01 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_currency_sell', models.CharField(blank=True, max_length=3, null=True)),
                ('preferred_currency_buy', models.CharField(blank=True, max_length=3, null=True)),
                ('avg_transaction_amount_cents', models.BigIntegerField(default=0)),
                ('total_transactions_count', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
