# Generated by Django 5.2.10 on 2026-07-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='completed_offers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='corridor_stats',
            field=models.JSONField(blank=True, default=dict, help_text="Stats par corridor 'SELL>BUY' : count, volume_cents, last_at"),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='disputes_count',
            field=models.IntegerField(default=0),
        ),
    ]
