# Generated by Django 5.2.10 on 2026-02-01 12:36

import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=50)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('offer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_cents', models.BigIntegerField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('details', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(help_text='Hash du log précédent', max_length=64)),
                ('hash', models.CharField(help_text='Hash actuel (Merckle like)', max_length=64)),
            ],
            options={
                'db_table': 'escrow_audit_logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_sell_cents', models.BigIntegerField(help_text='Montant vendu en centimes')),
                ('currency_sell', models.CharField(max_length=3)),
                ('amount_buy_cents', models.BigIntegerField(help_text='Montant souhaité en centimes')),
                ('currency_buy', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Taux: 1 Unit Sell = X Unit Buy', max_digits=10)),
                ('_beneficiary_data_encrypted', fernet_fields.fields.EncryptedTextField(blank=True, db_column='beneficiary_data', default='{}', help_text='Bénéficiaire désigné par le vendeur (B2) - Données chiffrées')),
                ('_accepted_beneficiary_data_encrypted', fernet_fields.fields.EncryptedTextField(blank=True, db_column='accepted_beneficiary_data', default='{}', help_text="Bénéficiaire désigné par l'acheteur (B1) - Données chiffrées")),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('ACCEPTED', 'Acceptée (En attente de fonds)'), ('LOCKED', 'Fonds Bloqués (Escrow)'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('EXPIRED', 'Expirée'), ('DISPUTE', 'En Litige')], db_index=True, default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_offers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('LOCKED', 'Verrouillé'), ('RELEASED', 'Libéré (Transféré)'), ('ROLLEDBACK', 'Remboursé (Annulation)')], default='LOCKED', max_length=20)),
                ('lock_hash', models.CharField(help_text='Hash SHA256 des données du lock pour intégrité', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Date limite avant auto-rollback')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_locks', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locks', to='Offer.offer')),
            ],
            options={
                'db_table': 'escrow_locks',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('under_review', 'Sous revue'), ('resolved', 'Résolu'), ('escalated', 'Escaladé (Support manuel)')], db_index=True, default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('refund_a1', 'Remboursement A1'), ('refund_a2', 'Remboursement A2'), ('split', 'Partage 50/50'), ('pending', 'En attente')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_initiated', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_reviewed', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='Offer.offer')),
            ],
            options={
                'db_table': 'offer_disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'currency_sell', 'currency_buy'], name='offers_status_62ab8e_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['expires_at'], name='offers_expires_96d9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowlock',
            index=models.Index(fields=['status', 'user'], name='escrow_lock_status_fe578e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['offer', 'status'], name='offer_dispu_offer_i_9818f0_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['initiated_by', 'created_at'], name='offer_dispu_initiat_6328dc_idx'),
        ),
    ]
