# Generated by Django 5.2.10 on 2026-02-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='b1_confirmed',
            field=models.BooleanField(default=False, help_text='Le bénéficiaire B1 a confirmé la réception/participation'),
        ),
        migrations.AddField(
            model_name='offer',
            name='b2_confirmed',
            field=models.BooleanField(default=False, help_text='Le bénéficiaire B2 a confirmé la réception/participation'),
        ),
    ]
