# Generated by Django 5.2.10 on 2026-02-09 20:49

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0002_offer_b1_confirmed_offer_b2_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='hash',
            field=models.CharField(help_text='Current hash (Merkle-like)', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(help_text='Previous log hash', max_length=64),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='resolution',
            field=models.CharField(blank=True, choices=[('refund_a1', 'Refund A1'), ('refund_a2', 'Refund A2'), ('split', '50/50 Split'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated (Manual support)')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrowlock',
            name='expires_at',
            field=models.DateTimeField(help_text='Deadline before auto-rollback'),
        ),
        migrations.AlterField(
            model_name='escrowlock',
            name='lock_hash',
            field=models.CharField(help_text='SHA256 hash of lock data for integrity', max_length=256),
        ),
        migrations.AlterField(
            model_name='escrowlock',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('RELEASED', 'Released (Transferred)'), ('ROLLEDBACK', 'Refunded (Cancellation)')], default='LOCKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='_accepted_beneficiary_data_encrypted',
            field=fernet_fields.fields.EncryptedTextField(blank=True, db_column='accepted_beneficiary_data', default='{}', help_text='Beneficiary designated by the buyer (B1) - Encrypted data'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='_beneficiary_data_encrypted',
            field=fernet_fields.fields.EncryptedTextField(blank=True, db_column='beneficiary_data', default='{}', help_text='Beneficiary designated by the seller (B2) - Encrypted data'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount_buy_cents',
            field=models.BigIntegerField(help_text='Desired amount in cents'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount_sell_cents',
            field=models.BigIntegerField(help_text='Amount sold in cents'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='b1_confirmed',
            field=models.BooleanField(default=False, help_text='Beneficiary B1 has confirmed receipt/participation'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='b2_confirmed',
            field=models.BooleanField(default=False, help_text='Beneficiary B2 has confirmed receipt/participation'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rate',
            field=models.DecimalField(decimal_places=6, help_text='Rate: 1 Unit Sell = X Unit Buy', max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted (Waiting for funds)'), ('LOCKED', 'Funds Locked (Escrow)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('DISPUTE', 'In Dispute')], db_index=True, default='OPEN', max_length=20),
        ),
    ]
