# Generated by Django 5.2.10 on 2026-01-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0002_dispute'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispute',
            new_name='offer_dispu_offer_i_9818f0_idx',
            old_name='offer_dispu_offer_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='dispute',
            new_name='offer_dispu_initiat_6328dc_idx',
            old_name='offer_dispu_initiat_created_idx',
        ),
    ]
