# Generated by Django 5.2.10 on 2026-01-30 19:40

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0003_rename_offer_dispu_offer_id_status_idx_offer_dispu_offer_i_9818f0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='accepted_beneficiary_data',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='beneficiary_data',
        ),
        migrations.AddField(
            model_name='offer',
            name='_accepted_beneficiary_data_encrypted',
            field=fernet_fields.fields.EncryptedTextField(blank=True, db_column='accepted_beneficiary_data', default='{}', help_text="Bénéficiaire désigné par l'acheteur (B1) - Données chiffrées"),
        ),
        migrations.AddField(
            model_name='offer',
            name='_beneficiary_data_encrypted',
            field=fernet_fields.fields.EncryptedTextField(blank=True, db_column='beneficiary_data', default='{}', help_text='Bénéficiaire désigné par le vendeur (B2) - Données chiffrées'),
        ),
    ]
