# Generated by Django 5.2.10 on 2026-01-30 17:14

import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('card', 'Carte bancaire'), ('bank_account', 'Compte bancaire'), ('orange_money', 'Orange Money')], max_length=20)),
                ('label', models.CharField(help_text="Nom donné par l'utilisateur", max_length=100)),
                ('card_last_four', models.CharField(blank=True, help_text='4 derniers chiffres', max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=50, null=True)),
                ('card_expiry_month', models.IntegerField(blank=True, help_text="Mois d'expiration (1-12)", null=True)),
                ('card_expiry_year', models.IntegerField(blank=True, help_text="Année d'expiration", null=True)),
                ('account_number', fernet_fields.fields.EncryptedCharField(blank=True, help_text='Numéro de compte (Chiffré)', max_length=150, null=True)),
                ('account_number_last_four', models.CharField(blank=True, help_text='4 derniers chiffres', max_length=4, null=True)),
                ('bank_code', models.CharField(blank=True, help_text='Code de la banque', max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Nom de la banque', max_length=200, null=True)),
                ('account_name', models.CharField(blank=True, help_text='Nom du titulaire', max_length=200, null=True)),
                ('bank_country', models.CharField(blank=True, help_text='Code pays de la banque', max_length=2, null=True)),
                ('orange_money_number', fernet_fields.fields.EncryptedCharField(blank=True, help_text='Numéro Orange Money (Chiffré)', max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Méthode par défaut pour ce type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('flutterwave_payment_method_id', models.CharField(blank=True, max_length=100, null=True)),
                ('flutterwave_recipient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(help_text='Devise du portefeuille (déterminée par le pays du numéro de téléphone)', max_length=3)),
                ('balance_cents', models.BigIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=0, help_text='Version pour le verrouillage optimiste')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait')], max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Carte bancaire'), ('orange_money', 'Orange Money')], max_length=20)),
                ('currency', models.CharField(help_text='Devise de la transaction', max_length=3)),
                ('amount_cents', models.BigIntegerField(help_text='Montant en centimes dans la devise locale')),
                ('fee_cents', models.BigIntegerField(default=0, help_text='Frais en centimes dans la devise locale')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Taux de conversion vers EUR (si applicable)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('flutterwave_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('flutterwave_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('flutterwave_event_id', models.CharField(blank=True, db_index=True, help_text="ID unique de l'événement webhook Flutterwave pour idempotence", max_length=100, null=True, unique=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('orange_money_number', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_adjusted', models.BooleanField(default=False, help_text='Vrai si le solde du wallet a été mis à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_proof', models.CharField(blank=True, help_text='Preuve de paiement (Flutterwave)', max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (JSON)')),
                ('payment_method_saved', models.ForeignKey(blank=True, help_text='Méthode de paiement sauvegardée utilisée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Wallet.paymentmethod')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Wallet.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'method_type', 'is_active'], name='payment_met_user_id_0be01b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='payment_met_user_id_332e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'is_active'], name='wallets_user_id_919dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency'], name='wallets_currenc_378bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['balance_cents'], name='wallets_balance_119e37_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance_cents__gte', 0)), name='positive_balance_constraint'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'status'], name='transaction_wallet__127b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_9f5934_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['currency'], name='transaction_currenc_cacf11_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['flutterwave_reference'], name='transaction_flutter_998309_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
    ]
