# Generated by Django 6.0 on 2026-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_adjusted',
            field=models.BooleanField(default=False, help_text='Vrai si le solde du wallet a été mis à jour'),
        ),
    ]
