# Generated by Django 5.2.10 on 2026-02-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('orange_money', 'Orange Money'), ('internal', 'Interne (Wallet)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('refund', 'Remboursement'), ('p2p_debit', 'Débit P2P'), ('p2p_credit', 'Crédit P2P')], max_length=20),
        ),
    ]
