# Generated by Django 5.2.10 on 2026-02-09 20:49

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_alter_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account holder name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Account number (Encrypted)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Bank code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_country',
            field=models.CharField(blank=True, help_text='Bank country code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_expiry_month',
            field=models.IntegerField(blank=True, help_text='Expiry month (1-12)', null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_expiry_year',
            field=models.IntegerField(blank=True, help_text='Expiry year', null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default method for this type'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='label',
            field=models.CharField(help_text='User-given name', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('card', 'Credit Card'), ('bank_account', 'Bank Account'), ('orange_money', 'Orange Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='orange_money_number',
            field=fernet_fields.fields.EncryptedCharField(blank=True, help_text='Orange Money number (Encrypted)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_cents',
            field=models.BigIntegerField(help_text='Amount in cents in local currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_adjusted',
            field=models.BooleanField(default=False, help_text='True if the wallet balance has been updated'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(help_text='Transaction currency', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Conversion rate to EUR (if applicable)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data (JSON)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_cents',
            field=models.BigIntegerField(default=0, help_text='Fees in cents in local currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='flutterwave_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID for the Flutterwave webhook event for idempotency', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('orange_money', 'Orange Money'), ('internal', 'Internal (Wallet)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method_saved',
            field=models.ForeignKey(blank=True, help_text='Saved payment method used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Wallet.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('p2p_debit', 'P2P Debit'), ('p2p_credit', 'P2P Credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_proof',
            field=models.CharField(blank=True, help_text='Payment proof (Flutterwave)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(help_text='Wallet currency (determined by phone number country)', max_length=3),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='version',
            field=models.IntegerField(default=0, help_text='Version for optimistic locking'),
        ),
    ]
