# Generated by Django 6.0 on 2026-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_transaction_balance_adjusted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (JSON)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_proof',
            field=models.CharField(blank=True, help_text='Preuve de paiement (Flutterwave)', max_length=255, null=True),
        ),
    ]
