# Generated by Django 6.0 on 2026-01-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_transaction_extra_data_transaction_transfer_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='version',
            field=models.IntegerField(default=0, help_text='Version pour le verrouillage optimiste'),
        ),
    ]
