# Generated by Django 6.0 on 2026-01-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_wallet_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='flutterwave_event_id',
            field=models.CharField(blank=True, db_index=True, help_text="ID unique de l'événement webhook Flutterwave pour idempotence", max_length=100, null=True, unique=True),
        ),
    ]
