# Generated by Django 6.0 on 2025-12-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
