# Generated by Django 5.2.10 on 2026-02-01 20:53

import Accounts.encrypted_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Face arrière (Chiffré)', null=True, storage=Accounts.encrypted_storage.EncryptedFileStorage(), upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='front_image',
            field=models.ImageField(help_text='Face avant du document (Chiffré)', storage=Accounts.encrypted_storage.EncryptedFileStorage(), upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='selfie_image',
            field=models.ImageField(blank=True, help_text='Selfie (Chiffré)', null=True, storage=Accounts.encrypted_storage.EncryptedFileStorage(), upload_to='kyc_selfies/'),
        ),
    ]
