# Generated by Django 6.0 on 2026-01-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_last_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_vendor_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
