# Generated by Django 6.0 on 2026-01-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_kycdocument_unique_user_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flutterwave_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
