# Generated by Django 5.2.10 on 2026-02-08 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_kycdocument_back_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(db_index=True, help_text='request_id de Didit', max_length=100)),
                ('didit_status', models.CharField(blank=True, help_text='Statut KYC (Approved, Declined, Pending)', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('payload_size', models.IntegerField(help_text='Taille du payload en bytes')),
                ('signature_valid', models.BooleanField(default=False)),
                ('signature_received', models.CharField(blank=True, help_text='Premiers caractères de la signature', max_length=100)),
                ('webhook_status', models.CharField(choices=[('received', 'Reçu'), ('signature_invalid', 'Signature Invalide'), ('processed', 'Traité avec succès'), ('failed', 'Échec de traitement')], default='received', max_length=20)),
                ('processing_duration_ms', models.IntegerField(blank=True, help_text='Durée de traitement en millisecondes', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict, help_text='Payload webhook complet')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur concerné (si trouvé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Audit Log',
                'verbose_name_plural': 'Webhook Audit Logs',
                'db_table': 'webhook_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_id'], name='webhook_aud_request_ec7811_idx'), models.Index(fields=['webhook_status', 'created_at'], name='webhook_aud_webhook_5181ce_idx'), models.Index(fields=['signature_valid', 'created_at'], name='webhook_aud_signatu_7a672e_idx')],
            },
        ),
    ]
