# Generated by Django 6.0 on 2025-12-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_profile_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={},
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='code',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='used',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='didit_session_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='didit_session_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='otpcode',
            table=None,
        ),
    ]
