# Generated by Django 5.2.10 on 2026-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_kycdocument_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kycdocument',
            new_name='kyc_documen_user_id_844d51_idx',
            old_name='kyc_documents_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='kycdocument',
            new_name='kyc_documen_created_4f4505_idx',
            old_name='kyc_documents_created_at_idx',
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Face arrière', null=True, upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='front_image',
            field=models.ImageField(help_text='Face avant du document', upload_to='kyc_documents/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='selfie_image',
            field=models.ImageField(blank=True, help_text='Selfie', null=True, upload_to='kyc_selfies/'),
        ),
    ]
